-- Schema for the NoteTaker application.
--
-- Apply this migration with the Supabase CLI (`supabase db push`) or by pasting
-- it into the project's SQL editor (Dashboard -> SQL Editor -> New query).

create table if not exists public.notes (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    content text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    email varchar(120) not null unique
);

-- Keep `updated_at` accurate for writes that bypass the application.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists notes_set_updated_at on public.notes;
create trigger notes_set_updated_at
    before update on public.notes
    for each row
    execute function public.set_updated_at();

create index if not exists notes_updated_at_idx
    on public.notes (updated_at desc);

-- The application reaches the database through PostgREST with an API key, so
-- row level security is always in play. These policies are deliberately
-- permissive because the app has no end-user accounts yet; replace them with
-- user-scoped policies once authentication is added (see README).
alter table public.notes enable row level security;
alter table public.users enable row level security;

drop policy if exists notes_api_access on public.notes;
create policy notes_api_access on public.notes
    for all to anon, authenticated
    using (true) with check (true);

drop policy if exists users_api_access on public.users;
create policy users_api_access on public.users
    for all to anon, authenticated
    using (true) with check (true);

-- Make the new tables visible to PostgREST without waiting for its cache to expire.
notify pgrst, 'reload schema';
